[package]
name = "car"
version = "0.0.0"
authors = ["William Cody Laeder, <codylaeder@gmail.com>"]

[dependencies]
nom = "2.1.0"
car_compress = { path = "car_compress" }
tar = { path = "tar-rs" }
walkdir = "1"
