[package]
name = "car"
version = "0.0.0"
authors = ["William Cody Laeder, <codylaeder@gmail.com>"]

[dependencies]
nom = "2.1.0"
car_compress = { path = "car_compress" }
car_cli = { path = "car_cli" }
tar = "0.4.10"
walkdir = "1"

[profile.release]
opt-level = 3
lto = true
