[package]
name = "lz4"
license = "MIT"
version = "1.20.0"
authors = [ "Artem V. Navrotskiy <bozaro@buzzsoft.ru>" ]
build = "build.rs"
description = "Rust LZ4 bindings library."
repository = "https://github.com/bozaro/lz4-rs"
documentation = "https://bozaro.github.io/lz4-rs/lz4/"

[[bin]]
name = "lz4"
test = false
doc = false

[dependencies]
libc = "0.2.17"
lz4-sys = { path = "lz4-sys", version = "1.0.1" }

[dev-dependencies]
rand = "0.3.14"
skeptic = "0.6.1"

[build-dependencies]
gcc = "0.3.38"
skeptic = "0.6.1"
